name: example
description: Example project for flutter_calendar_carousel.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_calendar_carousel:
    path: ../

flutter:

  uses-material-design: true

module:
  androidX: true